### ISSUE TITLE
trains-agent cannot run experimnent with uncommitted chagnes

### ISSUE THREAD

**Issue by gusido** [allegroai/trains-agent#12]
Hi,

I tried running a cloned experiment containing uncommitted code changes on a trains-agent and execution failed with "file not found" error.
can you advise?
Thanks!

**Comment by JDennisJ** [comment]
Hi @gusido ,

Can you attached some logs so we can analyze this issue? Does the task execution failed or the applying of the committed changes?

**Comment by gusido** [comment]
Hi @JDennisJ ,

there might have been an incosistency in my git repo. 
It is working find now.

thank you.
