### ISSUE TITLE
Init script shows git creds

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains-agent#13]
When running  `trains-agent init`, the console prompts git creds:

```
Enter git username for repository cloning (leave blank for SSH key authentication): [] {username}
Enter password for user 'h4dr1en': {password}.
Git repository cloning will be using user={username} password={password}
```

Password should be hidden (is visible currently)

**Comment by bmartinn** [comment]
Hi @H4dr1en ,

Thanks for the input! :)

This is actually on purpose. This value, although visible on-screen, will not be stored in the console history or any buffer. The reason for keeping it visible is that making any sort or mistake here is very unpleasant, and might cause confusion later on when trying to run experiments remotely.

Having said that, it's always preferred to use Git Keyring, in which case you won't have to provide user/password at all during trains-agent initialization (just press Enter and leave these values empty).

**Comment by H4dr1en** [comment]
Alright. 
By `Git Keyring`, do you using git over SSH?

**Comment by bmartinn** [comment]
Yes you are correct :)
