### ISSUE TITLE
Model.get_local_copy() returns empty directory

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains-agent#17]
## Context

Assuming a first task logs a model, a second task (cloned from the first one) tries to access to it:
```
parent_task = Task.get_task(Task.current_task().parent)
local_model = parent_task.models['output'][-1].get_local_copy()
logger.report_text(str(local_model))
```

The two tasks ran on the same agent, one after the other (the first one cloned itself and enqueued the second one). The first task finishes successfully:

```
020-05-18 14:20:34,261 - trains.Task - INFO - Completed model upload to file:///root/.trains/venvs-builds/3.6/task_repository/my-repo.git/checkpoint/test_conversion_pipeline/test_2.83871052c05c4f0a853a3870dbac302d/models/best_checkpoint_accuracy=0.0000.pt
2020-05-18 14:20:34,560 - trains.Task - INFO - Waiting to finish uploads
2020-05-18 14:20:48,567 - trains.Task - INFO - Finished uploading
```

Note: The saving of the models is handled by pytorch-ignite using TrainsSaver, every epoch. The files exist locally.

## Problem

The code above leads to the following warning when executed in the second task:
```
2020-05-18 15:04:32,203 - trains - WARNING - Exception [Errno 21] Is a directory: '/root/.trains/venvs-builds/3.6/task_repository/my-repo.git/checkpoint/test_conversion_pipeline/test_2.83871052c05c4f0a853a3870dbac302d/models/best_checkpoint_accuracy=0.0000.pt'
Failed extracting zip file /root/.trains/venvs-builds/3.6/task_repository/my-repo/checkpoint/test_conversion_pipeline/test_2.83871052c05c4f0a853a3870dbac302d/models/best_checkpoint_accuracy=0.0000.pt
```

Indeed the `local_model` is a path to an empty directory. 

## Config

```
agent.python_binary =
agent.package_manager.type = pip
agent.package_manager.pip_version = >\=20.1
```

**Comment by bmartinn** [comment]
Hi @H4dr1en 
The bug is verified, it is actually a *trains* bug. 
Just making sure I understand, there is a local file that should be accessible at `/root/.trains/venvs-builds/3.6/task_repository/my-repo.git/checkpoint/test_conversion_pipeline/test_2.83871052c05c4f0a853a3870dbac302d/models/best_checkpoint_accuracy=0.0000.pt`

The correct behavior should be:
`parent_task.models['output'][-1].get_local_copy()` returns the local path, or None (and prints a warning) if the local path does not exist.

We try not to raise exception on these things, so you do not have to wrap every such call in try/except block, and just check for None. That said, we do print a warning, so If you do try to pass the None to another function, you can understand why you got it in the first place.

Makes sense to you?

**Comment by H4dr1en** [comment]
> Just making sure I understand, there is a local file that should be accessible at /root/.trains/venvs-builds/3.6/task_repository/my-repo.git/checkpoint/test_conversion_pipeline/test_2.83871052c05c4f0a853a3870dbac302d/models/best_checkpoint_accuracy=0.0000.pt

Exactly, instead, this path points to an empty directory.

I would rather have an exception raised, because it is a critical point of my script: why whould I call `parent_task.models['output'][-1].get_local_copy()` without using it afterwards? This is a resource that I will need if I create it.

`get_local_copy(raise_on_failure=False)` Could be a middle-ground: Let users decide if this is critical for them to have the model.

**Comment by bmartinn** [comment]
@H4dr1en, sounds good , a fix will be included in the next RC (including the `raise_on_error` :)

**Comment by bmartinn** [comment]
Hi @H4dr1en , there is an RC with a fix out, would you care to test?
```console
pip install trains==0.15.0rc0
```

**Comment by H4dr1en** [comment]
Now it is failing with `trains==0.15.0rc0`, (because of `raise_on_error=True`) with the following error:

```
Retrieving model...
2020-05-24 11:39:32,731 - trains - WARNING - Failed accessing local file: file:///root/.trains/venvs-builds/3.6/task_repository/my-repo/checkpoint/test_conversion_pipeline/test_2.dcf4a719f7f94062a9f03ef4393123d9/models/best_checkpoint_accuracy=0.0000.pt
Traceback (most recent call last):
File "piping.py", line 105, in
main(parse_args)
File "piping.py", line 78, in main
local_model = parent_task.models['output'][-1].get_local_copy(raise_on_error=True)
File "/root/.trains/venvs-builds/3.6/lib/python3.6/site-packages/trains/model.py", line 432, in get_local_copy
return self.get_weights(raise_on_error=raise_on_error)
File "/root/.trains/venvs-builds/3.6/lib/python3.6/site-packages/trains/model.py", line 274, in get_weights
return self._get_base_model().download_model_weights(raise_on_error=raise_on_error)
File "/root/.trains/venvs-builds/3.6/lib/python3.6/site-packages/trains/backend_interface/model.py", line 425, in download_model_weights
"failed downloading {}".format(self.model_id, uri))
ValueError: Could not retrieve a local copy of model weights e25455c8d0a94233a3ba1db94374a2cb, failed downloading file:///root/.trains/venvs-builds/3.6/task_repository/my-repo/checkpoint/test_conversion_pipeline/test_2.dcf4a719f7f94062a9f03ef4393123d9/models/best_checkpoint_accuracy=0.0000.pt
```

**Comment by bmartinn** [comment]
Hi @H4dr1en 

Just making sure, the file `/root/.trains/venvs-builds/3.6/task_repository/my-repo/checkpoint/test_conversion_pipeline/test_2.dcf4a719f7f94062a9f03ef4393123d9/models/best_checkpoint_accuracy=0.0000.pt` exists in runtime ?

If it doesn't exists then raising an exception is the correct behavior if called with `raise_on_error=True`

**Comment by H4dr1en** [comment]
Hi @bmartinn,

Closing here, this time the bug was one my side 👍 

More details:
I was storing the model output locally in a relative path, which was appended to the current directory, which is the local git repository. I was expecting a second task to get the output model, but the agent simply removed the folder and cloned again the repo when running the second task (because it was the same repo), deleting the model outputs.
