### ISSUE TITLE
AutoML/cloning issue

### ISSUE THREAD

**Issue by majdzr** [allegroai/trains-agent#2]
When cloning a base experiment (e.g. automl_base_template_keras_simple) manually or automatically (e.g. with with automl_random_search_example), the trains agent catches it correctly and sets the relevant environment but then it fails to execute it. From LOG: 

> Environment setup completed successfully
> Starting Task Execution:
> Using TensorFlow backend.

and it stops here. no error but also no artifact.

**Comment by bmartinn** [comment]
Hi @majdzr , could you maybe attach the full log? 

Could it be that no git user/pass was provided to `trains_agent`? We are aware of this issue, `trains-agent` failing to clone repositories if credentials are not provided, even if the repository does not need any credtials.

There is already a fix for it, currently in RC, feel free to test it
`pip install trains_agent==0.12.1rc1`

**Comment by majdzr** [comment]
Thanks @bmartinn  for your reply. 
Indeed, the suggested fix (installing trains_agent==0.12.1rc1) solved the issue.
