### ISSUE TITLE
git creds are not used when install packages

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains-agent#22]
## Context

- An experiment lives in a private repo
- `agent.git_user` and `agent.git_pass` are configured in `trains.conf`
- This experiment is a python package installed at runtime
- This python package has dependencies
- Among the dependencies, one is another private repository

## Problem

`trains-agent`will successfully clone the private repo where the experiments lives using the git credentials configured. But it will fail installing the dependencies, because one of them is a private repo and `trains-agent` won't use the configured git credentials for the installation of the dependencies.

## Solution

`trains-agent` should use the git credentials for any git operation, regardless of when it happens.

**Comment by H4dr1en** [comment]
Workaround: Use [git-credential-cache](https://git-scm.com/docs/git-credential-cache) mechanism to cache the git credentials.

- Start the cache mechanism before calling `trains-agent` (below I am using root account and `--system` because I run the agent in a GCloud VM)
```
mkdir -p /root/git/credential
chmod 0700 /root/git/credential
git config --system credential.helper 'cache --socket /root/git/credential/socket'
```

- Start the agent. It will then pick a task. It will clone the experiment from the private repo using the git credentials. The latter will be stored in the cache. Therefore when trains-agent will install the dependencies of that task, it internally git will reuse its cache and voilà!

**Comment by bmartinn** [comment]
@H4dr1en wow! that is a great fix.
Did you have it as part of the bash script running on every docker?
(i.e. configured in the `~/trains.conf`, with [extra_docker_shell_script](https://github.com/allegroai/trains-agent/blob/master/docs/trains.conf#L99))
Or is it part of the GCP init script?

p.s.
The bug is verified :)

**Comment by H4dr1en** [comment]
This is part of the GCloud init script!

I avoided using docker so far because I am worried that containerd may decrease the overall performances during the training

**Comment by bmartinn** [comment]
> This is part of the GCloud init script!

Maybe we should run the same script from *trains-agent* when it starts, what do you think?

> I avoided using docker so far because I am worried that containered may decrease the overall performances during the training

Well, that's for nvidia to fix ;) 
BTW, someone just mentioned that https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL) might help ...

**Comment by H4dr1en** [comment]
> Maybe we should run the same script from trains-agent when it starts, what do you think?

Yes, this or any other mechanism that will reuse the git creds given by the user would be very nice! 
Note: The cache expires after 15 minutes by default (this value can be configured), which is fine for most cases.

> BTW, someone just mentioned that https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL) might help ...

Thanks for the link, I will have a look 👍

**Comment by H4dr1en** [comment]
By the way the hack mentionned above only works the first time you enqueue an experiment. If you reset/clone it and enqueue again, it may fail, because the dependency may then be installed before the actual repo of the experiment (which didn't happen before since it was installed after cloning the experiment repo)..

```
ERROR: Could not find a version that satisfies the requirement my-dependency-package (from -r /tmp/cached-reqsg6dplvj0.txt (line 26)) (from versions: none)
ERROR: No matching distribution found for my-dependency-package (from -r /tmp/cached-reqsg6dplvj0.txt (line 26))
```

**Comment by bmartinn** [comment]
@H4dr1en makes total sense :(
I think we will have to make sure we pass the correct git credentials for pip.
This means *trains-agent* will take this line:

```console
my-dependency-package @ git+https://github.com/H4dr1en/my-dependency-package@92kv9gk3b1cabf08a0b45d87fk3e70bd73a7bc94
```

and will pass to pip this line instead:

```console
my-dependency-package @ git+https://user:pass@github.com/H4dr1en/my-dependency-package@92kv9gk3b1cabf08a0b45d87fk3e70bd73a7bc94
```

**Comment by H4dr1en** [comment]
@bmartinn , is this solved by https://github.com/allegroai/trains-agent/commit/1f53a06299f90a9ff1d4bc6feebda1decaf5a4ba?

**Comment by bmartinn** [comment]
@H4dr1en yep :)

**Comment by H4dr1en** [comment]
Hi @bmartinn , I still experienced that issue with `trains-agent==0.16.3`: 
pip will fail to clone a private repository that is a requirement of the experiment, because the agent doesn't use the git creds.

requirement format:
```
install_requires=[...,
"private_package @ git+https://github.com/my-org/private-package@v1.0.0"
```

- git creds are passed via AWS AutoScaler (so in the agents, they are stored in `/root/trains.conf`
- `pip==20.2.3`

The workaround mentionned above still works

**Comment by bmartinn** [comment]
Hi @H4dr1en ,
Can you verify that the correct the `git_user` is used? Check the agent's log, at the beginning of the Task execution the agent's configuration is displayed, if everything is properly configured you should see there the "git_user" ("git_pass" will not be displayed for obvious security reasons)

**Comment by H4dr1en** [comment]
In the agent log, I can see the "git_user". Also the agent does use the creds to clone the private repository, that works fine.
The private repository of the experiment is a python package with a setup.py that references another private repo using `install_requires` (see my message above). That dependency cannot be cloned (git error 128) by pip, so I guess the agent is not using the git user/pass to process the private repository in the requirement, is this possible?

**Comment by bmartinn** [comment]
> hat dependency cannot be cloned (git error 128) by pip, so I guess the agent is not using the git user/pass to process the private repository in the requirement, is this possible?

Yes I think this is exactly it. We cannot pass the credentials to the derivative `git` call that pip is issueing.
That said, if you have `.git-credentials` file on he agent machine, then any `git` command will have the correct credentials, including the one pip will be calling. Even if the agent is running in docker-mode the  `.git-credentials` will be mounted into the docker meaning the `pip install git+` will work there as well.
WDYT?

**Comment by H4dr1en** [comment]
That's a good workaround yes (but requires to have the creds stored in a plain text file)
