### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by eliorc** [allegroai/trains-agent#30]
Under the section **AutoML and Orchestration Pipelines** in the README.md, all the links are broken.
3 of the references are nowhere to be found (looked their name up in the search box):

- [example/automl](https://github.com/allegroai/trains/tree/master/examples/automl)
- [Toy Keras training experiment](https://github.com/allegroai/trains/blob/master/examples/automl/automl_base_template_keras_simple.py)
- [Random Search over the above Keras experiment-template](https://github.com/allegroai/trains/blob/master/examples/automl/automl_random_search_example.py)

The last two are directed to wrong links, and I've created a PR to redirect them correctly

**Comment by bmartinn** [comment]
Thanks @eliorc , PR merged :)
