### ISSUE TITLE
How to use argparser?

### ISSUE THREAD

**Issue by majdzr** [allegroai/trains-agent#7]
I'm trying the following for semi-autoML, without any luck. Am I doing it wrong? argparse is one of the supported types for task.connect(), right?

```
parser = argparse.ArgumentParser()
...
opt = parser.parse_args()  
opt=task.connect(opt)
```
Error:
`Exception: Unsupported mutable type Namespace: no connect function found`

Thanks!

**Comment by JDennisJ** [comment]
Hi @majdzr,

Indeed you are right. The `connect` function support `ArgumentParser` as an argument, but no `Namespace`.
In the example you attached, it looks like you are trying to connect the result of `parse_args()` function, which is  `Namespace`. 

Can you try to connect the `parser` var in your example?

**Comment by majdzr** [comment]
Hi @JDennisJ ,

Thanks for your response. You are right, once I pass the parser it works. However, then: 
```
    opt=task.connect(parser)
    opt = functions.post_config(opt) # myfunction using opt
```
This code returns opt=None, and not the output of the parser.parse_args() that I was expecting, and therefore can't be used in the post_config function. Maybe I'm wrong, but I expected a similar behavior like in line 40-47 in trains/examples/automl/automl_base_template_keras_simple.py:
```
args = {'batch_size': 128,
        'epochs': 6,
        'layer_1': 512,
        'layer_2': 512,
        'layer_3': 10,
        'layer_4': 512,
        }
args = task.connect(args)
```

where the args are connected to the task and returned back, and once the task is cloned and the args are changed via the UI, they are still passed to rest of the code with the new values. 
What do I miss here? How to achieve similar behavior like the dict but with the parser?

Thanks in advance.

**Comment by JDennisJ** [comment]
Hi @majdzr ,

You are definitely right, for now `task.connect()` can return the original value or `None`. This can be very confusing, so in one of the coming versions this will be changed and `task.connect()` will always return value (and not `None`).

For now, please use this as a temporary workaround:
```
parser = argparse.ArgumentParser()
... 
task.connect(parser)
opt = parser.parse_args()
opt = functions.post_config(opt) 
```

Will keep you updated about this issue

**Comment by JDennisJ** [comment]
Hi @majdzr ,

Trains v0.13.3 was just released, with a fix for the connect with argparser :)

**Comment by majdzr** [comment]
Thank you!
